version: '3'

services:
  
  database:
    image: mariadb:latest
    restart: always
    volumes: 
      - "./images/sql:/docker-entrypoint-initdb.d"
    environment:
      MARIADB_ROOT_PASSWORD: password

  nginx:
    image: nginx:latest
    restart: always
    ports:
      - 8080:8080
    volumes:
      - ./www/static:/var/www/chess
      - ./images/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - database

  php-apache:
    hostname: mirea.dev
    build:
      ./images/php
    restart: always
    volumes:
      - ./www/dynamic:/var/www/chess
      - ./images/php/ports.conf:/etc/apache2/ports.conf
      - ./images/php/000-default.conf:/etc/apache2/sites-available/000-default.conf
    depends_on:
      - database
      - nginx