version: '3'

services:

  database:
    container_name: mysql
    image: mariadb:latest
    restart: always
    volumes: 
      - "./images/sql:/docker-entrypoint-initdb.d"
    environment:
      MARIADB_ROOT_PASSWORD: root
      MARIADB_USER: user
      MARIADB_PASSWORD: password
    healthcheck:
      test: "/usr/bin/mysql --user=user --password=password --execute \"SHOW DATABASES;\""
      interval: 3s
      timeout: 1s
      retries: 5

  php-apache:
    hostname: mirea.dev
    build:
      ./images/php
    volumes:
      - ./www/dynamic:/var/www/denis
      - ./images/php/ports.conf:/etc/apache2/ports.conf
      - ./images/php/000-default.conf:/etc/apache2/sites-available/000-default.conf
      - ./images/php/php.ini:/usr/local/etc/php/php.ini
    depends_on:
      database:
        condition: service_healthy
    healthcheck:
      test: "ls /var/www/denis/index.php"
      interval: 3s
      timeout: 1s
      retries: 5
  
  nginx:
    build: ./images/nginx
    restart: always
    ports:
      - 8080:8080
    volumes:
      - ./www/static:/var/www/denis
      - ./images/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      php-apache:
        condition: service_healthy

  redis:
    container_name: redis
    image: redis:alpine3.16
    restart: always
    ports:
      - "6379:6379"